import { Permission } from './types';

export const DISCORD_EPOCH = 1420070400000;

export const DISCORD_PERMISSIONS: Permission[] = [
  { name: 'Create Instant Invite', value: 1n << 0n, description: 'Allows creation of instant invites.' },
  { name: 'Kick Members', value: 1n << 1n, description: 'Allows kicking members.' },
  { name: 'Ban Members', value: 1n << 2n, description: 'Allows banning members.' },
  { name: 'Administrator', value: 1n << 3n, description: 'Allows all permissions and bypasses channel permission overwrites.' },
  { name: 'Manage Channels', value: 1n << 4n, description: 'Allows management and editing of channels.' },
  { name: 'Manage Server', value: 1n << 5n, description: 'Allows management and editing of the server.' },
  { name: 'Add Reactions', value: 1n << 6n, description: 'Allows for the addition of new reactions to messages.' },
  { name: 'View Audit Log', value: 1n << 7n, description: 'Allows for viewing of audit logs.' },
  { name: 'Priority Speaker', value: 1n << 8n, description: 'Allows for using priority speaker in a voice channel.' },
  { name: 'Stream', value: 1n << 9n, description: 'Allows the user to go live.' },
  { name: 'View Channel', value: 1n << 10n, description: 'Allows guild members to view a channel, which includes reading messages in text channels.' },
  { name: 'Send Messages', value: 1n << 11n, description: 'Allows for sending messages in a channel.' },
  { name: 'Send TTS Messages', value: 1n << 12n, description: 'Allows for sending of /tts messages.' },
  { name: 'Manage Messages', value: 1n << 13n, description: 'Allows for deletion of other users messages or pinning messages.' },
  { name: 'Embed Links', value: 1n << 14n, description: 'Links sent by users with this permission will be auto-embedded.' },
  { name: 'Attach Files', value: 1n << 15n, description: 'Allows for uploading images and files.' },
  { name: 'Read Message History', value: 1n << 16n, description: 'Allows for reading of message history.' },
  { name: 'Mention Everyone', value: 1n << 17n, description: 'Allows for using the @everyone tag to notify all users in a channel, and also allows for any role to be mentioned.' },
  { name: 'Use External Emojis', value: 1n << 18n, description: 'Allows the usage of custom emojis from other servers.' },
  { name: 'View Server Insights', value: 1n << 19n, description: 'Allows for viewing of guild insights.' },
  { name: 'Connect', value: 1n << 20n, description: 'Allows for joining of a voice channel.' },
  { name: 'Speak', value: 1n << 21n, description: 'Allows for speaking in a voice channel.' },
  { name: 'Mute Members', value: 1n << 22n, description: 'Allows for muting members in a voice channel.' },
  { name: 'Deafen Members', value: 1n << 23n, description: 'Allows for deafening of members in a voice channel.' },
  { name: 'Move Members', value: 1n << 24n, description: 'Allows for moving of members between voice channels.' },
  { name: 'Use VAD', value: 1n << 25n, description: 'Allows for using voice-activity-detection in a voice channel.' },
  { name: 'Change Nickname', value: 1n << 26n, description: 'Allows for modification of own nickname.' },
  { name: 'Manage Nicknames', value: 1n << 27n, description: 'Allows for modification of other users nicknames.' },
  { name: 'Manage Roles', value: 1n << 28n, description: 'Allows management and editing of roles.' },
  { name: 'Manage Webhooks', value: 1n << 29n, description: 'Allows management and editing of webhooks.' },
  { name: 'Manage Guild Expressions', value: 1n << 30n, description: 'Allows management and editing of emojis, stickers, and soundboard sounds.' },
  { name: 'Use Application Commands', value: 1n << 31n, description: 'Allows members to use application commands, including slash commands and context menu commands.' },
  { name: 'Request to Speak', value: 1n << 32n, description: 'Allows for requesting to speak in stage channels.' },
  { name: 'Manage Events', value: 1n << 33n, description: 'Allows for creating, editing and deleting scheduled events.' },
  { name: 'Manage Threads', value: 1n << 34n, description: 'Allows for deleting and archiving threads, and viewing all private threads.' },
  { name: 'Create Public Threads', value: 1n << 35n, description: 'Allows for creating public and announcement threads.' },
  { name: 'Create Private Threads', value: 1n << 36n, description: 'Allows for creating private threads.' },
  { name: 'Use External Stickers', value: 1n << 37n, description: 'Allows the usage of custom stickers from other servers.' },
  { name: 'Send Messages in Threads', value: 1n << 38n, description: 'Allows for sending messages in threads.' },
  { name: 'Use Embedded Activities', value: 1n << 39n, description: 'Allows for using Activities (applications with the EMBEDDED flag) in a voice channel.' },
  { name: 'Moderate Members', value: 1n << 40n, description: 'Allows for timing out users to prevent them from sending or reacting to messages in chat and threads, and from speaking in voice and stage channels.' },
  { name: 'View Creator Monetization Analytics', value: 1n << 41n, description: 'Allows for viewing role subscription insights.' },
  { name: 'Use Soundboard', value: 1n << 42n, description: 'Allows for using soundboard in a voice channel.' },
  { name: 'Use External Sounds', value: 1n << 45n, description: 'Allows the usage of custom soundboard sounds from other servers.' },
  { name: 'Send Voice Messages', value: 1n << 46n, description: 'Allows for sending voice messages.' },
];
